/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PdfEditorRouteImport } from './routes/pdf-editor'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReportAbuseRouteImport } from './routes/report-abuse'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PdfSlugRouteImport } from './routes/pdf.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfEditorRoute = PdfEditorRouteImport.update({
  id: '/pdf-editor',
  path: '/pdf-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportAbuseRoute = ReportAbuseRouteImport.update({
  id: '/report-abuse',
  path: '/report-abuse',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfSlugRoute = PdfSlugRouteImport.update({
  id: '/pdf/$slug',
  path: '/pdf/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/pdf-editor': typeof PdfEditorRoute
  '/privacy': typeof PrivacyRoute
  '/report-abuse': typeof ReportAbuseRoute
  '/terms': typeof TermsRoute
  '/pdf/$slug': typeof PdfSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/pdf-editor': typeof PdfEditorRoute
  '/privacy': typeof PrivacyRoute
  '/report-abuse': typeof ReportAbuseRoute
  '/terms': typeof TermsRoute
  '/pdf/$slug': typeof PdfSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/pdf-editor': typeof PdfEditorRoute
  '/privacy': typeof PrivacyRoute
  '/report-abuse': typeof ReportAbuseRoute
  '/terms': typeof TermsRoute
  '/pdf/$slug': typeof PdfSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/pdf-editor'
    | '/privacy'
    | '/report-abuse'
    | '/terms'
    | '/pdf/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/pdf-editor'
    | '/privacy'
    | '/report-abuse'
    | '/terms'
    | '/pdf/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/pdf-editor'
    | '/privacy'
    | '/report-abuse'
    | '/terms'
    | '/pdf/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PdfEditorRoute: typeof PdfEditorRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportAbuseRoute: typeof ReportAbuseRoute
  TermsRoute: typeof TermsRoute
  PdfSlugRoute: typeof PdfSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-editor': {
      id: '/pdf-editor'
      path: '/pdf-editor'
      fullPath: '/pdf-editor'
      preLoaderRoute: typeof PdfEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-abuse': {
      id: '/report-abuse'
      path: '/report-abuse'
      fullPath: '/report-abuse'
      preLoaderRoute: typeof ReportAbuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf/$slug': {
      id: '/pdf/$slug'
      path: '/pdf/$slug'
      fullPath: '/pdf/$slug'
      preLoaderRoute: typeof PdfSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PdfEditorRoute: PdfEditorRoute,
  PrivacyRoute: PrivacyRoute,
  ReportAbuseRoute: ReportAbuseRoute,
  TermsRoute: TermsRoute,
  PdfSlugRoute: PdfSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
